version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: fantasy_postgres
    environment:
      POSTGRES_DB: fantasy_db
      POSTGRES_USER: fantasy_user
      POSTGRES_PASSWORD: fantasy_dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fantasy_user -d fantasy_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
